(defun toss-coin ()
	 (let ((number (random 2 (make-random-state t))))
	 ;	(format t "Number is: ~A~%" number)
	 	(if (= number 0) "heads" "tails")
	 )
)
(defun prompt ()
  	(format t "Please enter 'heads' or 'tails': ")
	(force-output)

	(let ((guess (string-downcase(read-line))))
		  (if (or (string= guess "heads") (string= guess "tails"))
				guess
				(prompt)
			)
	   )
)
(defun game ()					; run from here as (game)
  	(if (string= (prompt)
				 (toss-coin)
		 )
	  	(format t "You Win!~%")
		(format t "You Lose!~%")
	  )
  )
